### ISSUE TITLE
Failed to use jwt authentication in swagger

### ISSUE THREAD

**Issue by npuichigo** [sapati/shelter-project#3]
After setting global jwt token for swagger
![微信截图_20240112210629](https://github.com/sapati/shelter-project/assets/11533479/9a2cd200-aa6f-4ae4-bbe2-f88d80405369)

Try it now still failed with 401 Unauthorized.
![微信截图_20240112210649](https://github.com/sapati/shelter-project/assets/11533479/317db592-350b-4d11-98e0-59fc34d22870)

**Comment by sapati** [comment]
I had to change the utoipa settings a little, added the security part:

```
#[utoipa::path(
    post,
    path = "/dogs",
    tag = "dogs",
    request_body = DogCreateRequest,
    responses(
        (status = 200, description = "Dog create", body = DogCreateResponse),
        (status = 401, description = "Missing bearer token", body = ErrorResponse),
    ),
    security(
        ("api_jwt_token" = [])
    ),
)]
#[debug_handler]
#[instrument(level = "info", name = "create_dog", skip_all)]
pub async fn create() {}
```
