### ISSUE TITLE
Support tracing HTTP request and show related span?

### ISSUE THREAD

**Issue by npuichigo** [sapati/shelter-project#4]
For example, `list_dogs` is only showed without info related to the HTTP request
![image](https://github.com/sapati/shelter-project/assets/11533479/863ead4c-a0f9-4f03-a9d8-ed0534198463)

After using [axum-tracing-opentelemtry](https://crates.io/crates/axum-tracing-opentelemetry), which adds a layer `OtelAxumLayer` to start span on incoming request, still no http span is showed. 

Until `init_tracing_opentelemetry::tracing_subscriber_ext::init_subscribers()?;` it works then
![image](https://github.com/sapati/shelter-project/assets/11533479/131da410-9698-4eb1-ab3a-dbdbc01abe37)

I have no idea what's missing in setup opentelemetry here, hence let me to use `init_tracing_opentelemetry`

**Comment by sapati** [comment]
Hi, the http span is created at the TRACING level but I set a DEBUG level filter here:

```
let telemetry_layer = tracing_opentelemetry::layer().with_tracer(tracer);
let subscriber = tracing_subscriber::registry()
    .with(LevelFilter::from_level(Level::DEBUG))
    .with(telemetry_layer);
```

Change the level to TRACING or remove the filter and I think the http span will show up in the collector.
